{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.shirokuro",
    "module": "worlds",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "nwlvj2mzyzdchm3ml6fwpcf4he"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "worlds-0.3.0.jar",
          "url": "worlds-0.3.0.jar",
          "size": 35295,
          "sha512": "42bac9fa47f053d92eba1f960eef4248492caa025b036bdcfec931b76f7e7cce5ab044391e7140d0cc93c016feb2277d4096566e5133c7dbe636fdfb78496e14",
          "sha256": "0352c881521f2fad7ae221cad5d584c0b674ff6453f25b90c839c73b718b42b9",
          "sha1": "a6f2413fd54a8fcd20171347af71431f59119993",
          "md5": "384b8f0c65bac4226cfd8cb1af2f8d39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xyz.shirokuro",
          "module": "commandutility",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "worlds-0.3.0.jar",
          "url": "worlds-0.3.0.jar",
          "size": 35295,
          "sha512": "42bac9fa47f053d92eba1f960eef4248492caa025b036bdcfec931b76f7e7cce5ab044391e7140d0cc93c016feb2277d4096566e5133c7dbe636fdfb78496e14",
          "sha256": "0352c881521f2fad7ae221cad5d584c0b674ff6453f25b90c839c73b718b42b9",
          "sha1": "a6f2413fd54a8fcd20171347af71431f59119993",
          "md5": "384b8f0c65bac4226cfd8cb1af2f8d39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "worlds-0.3.0-javadoc.jar",
          "url": "worlds-0.3.0-javadoc.jar",
          "size": 439506,
          "sha512": "74112422daf884072340adfaa16dfca5df4008cdbd4adb2c00efb119dcbfbc468bef317ff113d1bb70a1cb9d19b3857209786a5841a1b21b7f9d6c7662a99717",
          "sha256": "5f4df15f7c260c0c2cb43277b036e3fbec745ccf2ed8c2acaa95c58a3a06280e",
          "sha1": "32d2d9c21852e2a1309487cc563af3fcb8992cd7",
          "md5": "c4fe695584473a90f5749ce0ff6d51d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "worlds-0.3.0-sources.jar",
          "url": "worlds-0.3.0-sources.jar",
          "size": 15650,
          "sha512": "14b45e826181b0a0e6ba8d902cedb8d39d039302f3c0102056558fb64aa81a22c8b8cfa65c800495d6e2c93371f7bed91b00fcaa92f3f03e1150b2af91de9369",
          "sha256": "aaf4df4192a4ad2a28f03c321ee56f68fcdaaf945cdfe3d25d9ab9a288bde4f3",
          "sha1": "10d31c34856f5ab1785addd5d95b578f7fed8a9d",
          "md5": "e68305b877cbdea87ce14b0d7b000213"
        }
      ]
    }
  ]
}
