{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.shirokuro",
    "module": "commandutility",
    "version": "0.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "mdege67325bflpjr35ywmvlk2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "commandutility-0.6.0-SNAPSHOT.jar",
          "url": "commandutility-0.6.0-SNAPSHOT.jar",
          "size": 18582,
          "sha512": "2c791a3a0aebff89ed722daad1799d8e2d53d1b15f5c4bc04e7b36e578614eb9f0ae9f3f701eb5eb0e2b7aef2e1fc15d30a914be7fc38821eb4c014cbb43530f",
          "sha256": "9921ef94639824cac177cc990e18242b671d5d3fbb02601c321077b7e0e28fd3",
          "sha1": "6a143fb8025da717cf10f326f59dadb91c71eaca",
          "md5": "41bafe9d958b73b6ed859a9775e731fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "commandutility-0.6.0-SNAPSHOT.jar",
          "url": "commandutility-0.6.0-SNAPSHOT.jar",
          "size": 18582,
          "sha512": "2c791a3a0aebff89ed722daad1799d8e2d53d1b15f5c4bc04e7b36e578614eb9f0ae9f3f701eb5eb0e2b7aef2e1fc15d30a914be7fc38821eb4c014cbb43530f",
          "sha256": "9921ef94639824cac177cc990e18242b671d5d3fbb02601c321077b7e0e28fd3",
          "sha1": "6a143fb8025da717cf10f326f59dadb91c71eaca",
          "md5": "41bafe9d958b73b6ed859a9775e731fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "commandutility-0.6.0-SNAPSHOT-sources.jar",
          "url": "commandutility-0.6.0-SNAPSHOT-sources.jar",
          "size": 8098,
          "sha512": "9e931eab07fddd27b7ca2a3ba17420391b8f40fe9cbea324edf044b6ff4d05a3c835afe0726d7e72c8f48964dbf2d9162a7a014768d9e8067e1ab68bea7adc42",
          "sha256": "bdd19f9b3d46810fc854b0a02dc016169837a9cd39f90d3202ca9c807d5095a6",
          "sha1": "2596742b95536d789017fccb742614c053997c55",
          "md5": "c078711ff6acf66b117fac7d01eb479f"
        }
      ]
    }
  ]
}
